#!/bin/sh
#make distclean
#echo "compiling for linux"
#./autogen.sh
#./configure --disable-tests --disable-bench
#make -j6
#cp ./src/hemisd ./hemisd
#cp ./src/hemis-cli ./hemis-cli



echo "Compiling for Windows"
make distclean
PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
cd depends
make HOST=x86_64-w64-mingw32 -j6
cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/ --disable-online-rust --disable-tests --disable-bench
make -j6
make deploy

