#!/bin/sh
make distclean
echo "compiling for linux"
./autogen.sh
./configure --disable-tests --disable-bench --enable-mining-rpc --enable-debug
make -j6
cp ./src/Hemisd ./Hemisd
cp ./src/Hemis-cli ./Hemis-cli
