#!/bin/sh
cores=$(getconf _NPROCESSORS_ONLN)
echo "We have "$cores" Cores"
TIMEFORMAT='It took %R seconds to build Hemis.'
time {
make distclean
echo "compiling for linux"
./autogen.sh
./configure --disable-tests --disable-bench --enable-mining-rpc --disable-debug
make -j$cores

cp ./src/Hemisd /var/www/html/builds/linux/Hemisd
cp ./src/Hemis-cli /var/www/html/builds/linux/Hemis-cli
cp ./src/Hemis-tx /var/www/html/builds/linux/Hemis-tx
cp ./src/qt/Hemis-qt /var/www/html/builds/linux/Hemis-qt

echo "Compiling for Windows"
make distclean
PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
cd depends
make HOST=x86_64-w64-mingw32 -j$cores
cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/ --disable-online-rust --disable-tests --disable-bench
make -j$cores
make deploy

cp ./src/Hemisd.exe /var/www/html/builds/windows/Hemisd.exe
cp ./src/Hemis-cli.exe /var/www/html/builds/windows/Hemis-cli.exe
cp ./src/Hemis-tx.exe /var/www/html/builds/windows/Hemis-tx.exe

cp ./src/qt/Hemis-qt.exe /var/www/html/builds/windows/Hemis-qt.exe
cp ./Hemis-*-win64-setup-unsigned.exe /var/www/html/builds/windows/Hemis-installer.exe
Hemis-1.0.0rc1-win64-setup.exe

echo "Compiling for ARM"
make distclean
echo "Compiling for ARM"
cd depends
make HOST=arm-linux-gnueabihf NO_QT=1 -j$cores
cd ..
./autogen.sh
./configure --prefix=$PWD/depends/arm-linux-gnueabihf --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++ --disable-tests --disable-bench
make -j$cores

cp ./src/Hemisd /var/www/html/builds/arm/Hemisd
cp ./src/Hemis-cli /var/www/html/builds/arm/Hemis-cli
cp ./src/Hemis-tx /var/www/html/builds/arm/Hemis-tx
